USE FidelitasHub;
GO

BEGIN TRANSACTION;

INSERT INTO Clients
(
    ClientCode,
    ClientName,
    IsActive,
    CreatedOn,
    CreatedBy
)
VALUES
('ADULTPC', 'ADULT PRIMARY CARE PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('ARH', 'ADVANCED RESTORATIVE HEALTH', 1, GETDATE(), 'Phase 4 Seed'),
('ADVNP', 'ADVANCEDNP', 1, GETDATE(), 'Phase 4 Seed'),
('ABMH', 'ANCHOR BEHAVIORAL AND MENTAL HEALTH SERVICES LLC', 1, GETDATE(), 'Phase 4 Seed'),
('AUSTINPC', 'AUSTIN PULMONARY CONSULTANTS PA', 1, GETDATE(), 'Phase 4 Seed'),
('BHC', 'BEHAVIORAL HEALTH CONSULTANTS', 1, GETDATE(), 'Phase 4 Seed'),
('BONMED', 'BON-MED HYPERBARIC AND WOUND CARE', 1, GETDATE(), 'Phase 4 Seed'),
('BOOMER', 'BOOMER REHAB CONSULTING PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('CTHP', 'CENTRAL TEXAS HOSPITAL PHYSICIANS PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('CTMH', 'CENTRAL TEXAS MENTAL HEALTH PA', 1, GETDATE(), 'Phase 4 Seed'),
('CPS', 'COMPREHENSIVE PSYCHOLOGICAL SERVICES, LTD.', 1, GETDATE(), 'Phase 4 Seed'),
('CFMD', 'CRAIG FRANKE MD', 1, GETDATE(), 'Phase 4 Seed'),
('DAVID', 'DAVID MORLEDGE MD PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('DDRG', 'DDRG PHYSICIANS LLC', 1, GETDATE(), 'Phase 4 Seed'),
('FAHEEM', 'FAHEEM AHMED MD PA PC', 1, GETDATE(), 'Phase 4 Seed'),
('GPS', 'GERIATRIC POST ACUTE SPECIALISTS', 1, GETDATE(), 'Phase 4 Seed'),
('HIT', 'HOSPITAL INTERNISTS OF TEXAS, LLC', 1, GETDATE(), 'Phase 4 Seed'),
('IDOCS', 'IDOCSWEB LLC', 1, GETDATE(), 'Phase 4 Seed'),
('IHC', 'INHOME CONNECT OF FORT WORTH', 1, GETDATE(), 'Phase 4 Seed'),
('KUYE', 'KUYE MEDICAL GROUP', 1, GETDATE(), 'Phase 4 Seed'),
('LKG', 'LAURA K GILBEY MD PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('MHP', 'MERIDIAN HEALTH PARTNERS PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('MPAC', 'MIDWEST POST ACUTE CARE PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('NAPA', 'NORTH ARLINGTON PULMONARY ASSOCIATES', 1, GETDATE(), 'Phase 4 Seed'),
('NLFM', 'NORTH LAMAR FAMILY MEDICINE', 1, GETDATE(), 'Phase 4 Seed'),
('NWG', 'NW GERIATRICS PA', 1, GETDATE(), 'Phase 4 Seed'),
('PADMA', 'PADMA K HORVIT MD PA', 1, GETDATE(), 'Phase 4 Seed'),
('PATHWAY', 'PATHWAY HEALTH LLC', 1, GETDATE(), 'Phase 4 Seed'),
('PCMAPD', 'PCMA PALLIATIVE DIVISION LLC', 1, GETDATE(), 'Phase 4 Seed'),
('PCMAGER', 'PERSONAL CARE MEDICAL ASSOCIATES LLC', 1, GETDATE(), 'Phase 4 Seed'),
('PHYFIRST', 'PHYSIATRY FIRST PA', 1, GETDATE(), 'Phase 4 Seed'),
('PLATINUM', 'PLATINUM PSYCHOLOGY SERVICES INC', 1, GETDATE(), 'Phase 4 Seed'),
('PRUITT', 'PRUITTHEALTH PHYSICIANS SERVICES, LLC', 1, GETDATE(), 'Phase 4 Seed'),
('PGS', 'PSYCHOGERIATRIC SERVICES LLC', 1, GETDATE(), 'Phase 4 Seed'),
('RHILLS', 'ROLLING HILLS BEHAVIORAL HEALTH', 1, GETDATE(), 'Phase 4 Seed'),
('SEEGOTT', 'SEEGOTT HEALTH LLC', 1, GETDATE(), 'Phase 4 Seed'),
('SHANNON', 'SHANNONDELL HEALTH', 1, GETDATE(), 'Phase 4 Seed'),
('SHELLY', 'SHELLY COX LCSW', 1, GETDATE(), 'Phase 4 Seed'),
('SUNCITY', 'SUN CITY NEUROMUSCULAR REHABILITATION PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('SUPRIYA', 'SUPRIYA SHAH MD PA', 1, GETDATE(), 'Phase 4 Seed'),
('TOTALCARE', 'TOTAL CARE FAMILY PRACTICE RICK BOBAY LLC', 1, GETDATE(), 'Phase 4 Seed'),
('TRINITY', 'TRINITY POST-ACUTE CARE PA', 1, GETDATE(), 'Phase 4 Seed'),
('TPA', 'TRUMEN PHYSICIANS AND ASSOCIATES PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('VINOD', 'VINOD K. VALIVETI M.D. INC.', 1, GETDATE(), 'Phase 4 Seed'),
('WEHP', 'WELLNESS ELITE HEALTH PARTNERS, LLC', 1, GETDATE(), 'Phase 4 Seed'),
('WCFM', 'WOUND CARE AND FAMILY MEDICINE', 1, GETDATE(), 'Phase 4 Seed'),
('ZIBA', 'ZIBA REZAEE MD PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('CGI', 'COLLABORATIVE GERIATRICS INC', 1, GETDATE(), 'Phase 4 Seed'),
('HFC', 'HECTOR F COLON MD PA', 1, GETDATE(), 'Phase 4 Seed'),
('GSC/DME', 'GEORGETOWN SLEEP CENTER, P.A.', 1, GETDATE(), 'Phase 4 Seed'),
('PSNWI', 'PULMONARY SPECIALISTS OF NW INDIANA', 1, GETDATE(), 'Phase 4 Seed'),
('GPA', 'GEORGETOWN PULMONARY ASSOCIATES PA', 1, GETDATE(), 'Phase 4 Seed'),
('CIWC', 'COLLEAGUES IN WOUND CARE', 1, GETDATE(), 'Phase 4 Seed'),
('TBC', 'THE BRADLEY CLINIC OF TEXAS PLLC', 1, GETDATE(), 'Phase 4 Seed'),
('PKMD', 'PALLAVI KAKULAVAR MD PA', 1, GETDATE(), 'Phase 4 Seed'),
('CARE TIME', 'CARE TIME', 1, GETDATE(), 'Phase 4 Seed');

-- Verify before committing
SELECT
    ClientId,
    ClientCode,
    ClientName,
    IsActive
FROM Clients
ORDER BY ClientId;

-- Confirm exactly 56 records were inserted
SELECT COUNT(*) AS InsertedClientCount
FROM Clients
WHERE CreatedBy = 'Phase 4 Seed';

COMMIT TRANSACTION;
GO